---
- name: restart uptime-kuma
  community.docker.docker_container:
    name: "{{ uptime_kuma_container_name }}"
    restart: true

- name: test nginx config
  ansible.builtin.command: nginx -t
  register: nginx_test_result
  failed_when: nginx_test_result.rc != 0
  listen: "test nginx config"

- name: reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
  when: nginx_test_result is not defined or nginx_test_result.rc == 0
  listen: "reload nginx"
