kardiai_proxy_hosts:
  - api.kardi-ai.com
  - mb.kardi-ai.com
  - web.kardi-ai.com
  - partner.kardi-ai.com
  - pay.kardi-ai.com
  - api.eu.kardi-ai.com
  - mb.eu.kardi-ai.com
  - web.eu.kardi-ai.com
  - partner.eu.kardi-ai.com
  - pay.eu.kardi-ai.com

# internal loadbalancer DNS
upstream: "k8s-ingressi-ingressi-feadfdf02b-944feeca46f8d73f.elb.eu-central-1.amazonaws.com"
