[kardi_monitoring]
de.mon.kardi-ai.org ansible_user=jarekmacku
sg.mon.kardi-ai.org ansible_user=jarekmacku

[kardi_proxy]
proxy.sg.test.kardi-ai.org ansible_host=18.136.169.176 ansible_user=admin
proxy.sg.prod.kardi-ai.org ansible_host=52.74.117.163 ansible_user=admin

[uptime]
de.mon.kardi-ai.org ansible_user=jarekmacku

[all:vars]
ansible_python_interpreter=/usr/bin/python3
