## Kardi AI web presentation
- targets:
    - https://kardi.ai
    - https://kardi-ai.com
  labels:
    environment: "Website"
    reporter: "Germany"

- targets:
    - https://status.kardi-ai.com
  labels:
    environment: "Infrastructure"
    reporter: "Germany"

## EU Test env
- targets:
  ## API services
  - https://api.eu.kardi-ai.org/api/v1/general/liveness-probe
  - https://partner.eu.kardi-ai.org/api/v2/general/health-check
  - https://mb.eu.kardi-ai.org/api/v1/general/liveness-probe
  ## web services
  #- https://web.eu.kardi-ai.org
  - https://web.eu.kardi-ai.org/static/favicon.e68d001a9fb1.svg
  - https://pay.eu.kardi-ai.org
  labels:
    environment: "Test EU"
    reporter: "Germany"

## EU Training env
- targets:
  ## API services
  - https://api.eu.ait.kardi-ai.org/api/v1/general/liveness-probe
  - https://mb.eu.ait.kardi-ai.org/api/v1/general/liveness-probe
  ## web services
  #- https://web.eu.ait.kardi-ai.org
  - https://web.eu.ait.kardi-ai.org/static/favicon.e68d001a9fb1.svg
  - https://pay.eu.ait.kardi-ai.org
  labels:
    environment: "Training EU"
    reporter: "Germany"

## EU Production
- targets:
  ## API services
  - https://api.eu.kardi-ai.com/api/v1/general/liveness-probe
  - https://partner.eu.kardi-ai.com/api/v2/general/health-check
  - https://mb.eu.kardi-ai.com/api/v1/general/liveness-probe
  ## web services
  #- https://web.eu.kardi-ai.com
  - https://web.eu.kardi-ai.com/static/favicon.e68d001a9fb1.svg
  - https://pay.eu.kardi-ai.com
  labels:
    environment: "Production EU"
    reporter: "Germany"

### UAE Production
#- targets:
#  ## API services
#  - https://api.ae.kardi-ai.com/api/v1/general/liveness-probe
#  - https://partner.ae.kardi-ai.com/api/v2/general/health-check
#  - https://mb.ae.kardi-ai.com/api/v1/general/liveness-probe
#  ## web services
#  #- https://web.ae.kardi-ai.com
#  - https://web.ae.kardi-ai.com/static/favicon.e68d001a9fb1.svg
#  - https://pay.ae.kardi-ai.com
#  labels:
#    environment: "Production UAE"
#    reporter: "Germany"
#
### UAE Test
#- targets:
#    ## API services
#    - https://api.ae.test.kardi-ai.org/api/v1/general/liveness-probe
#    - https://partner.ae.test.kardi-ai.org/api/v2/general/health-check
#    - https://mb.ae.test.kardi-ai.org/api/v1/general/liveness-probe
#    ## web services
#    #- https://web.ae.test.kardi-ai.org
#    - https://web.ae.test.kardi-ai.org/static/favicon.e68d001a9fb1.svg
#    - https://pay.ae.test.kardi-ai.org
#  labels:
#    environment: "Test UAE"
#    reporter: "Germany"