---
- name: Install UFW if missing
  ansible.builtin.apt:
    name: ufw
    state: latest
    update_cache: yes

- name: Install Fail2Ban package
  ansible.builtin.apt:
    name: fail2ban
    state: latest
    update_cache: yes

- name: Deploy Fail2Ban jail configuration
  ansible.builtin.template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: '0644'
  notify: restart fail2ban

- name: Ensure Fail2Ban service is enabled and running
  ansible.builtin.service:
    name: fail2ban
    enabled: yes
    state: started
