---
- name: Install WireGuard package
  ansible.builtin.apt:
    name: wireguard
    state: latest
    update_cache: yes

- name: Deploy WireGuard privatekey
  ansible.builtin.template:
    src: private.key.j2
    dest: "/etc/wireguard/private.key"
    owner: root
    group: root
    mode: '0600'
  notify: restart wireguard

- name: Deploy WireGuard publickey
  ansible.builtin.template:
    src: public.key.j2
    dest: "/etc/wireguard/public.key"
    owner: root
    group: root
    mode: '0600'
  notify: restart wireguard

- name: Deploy WireGuard configuration
  ansible.builtin.template:
    src: wg0.conf.j2
    dest: "/etc/wireguard/{{ wireguard_interface }}.conf"
    owner: root
    group: root
    mode: '0600'
  notify: restart wireguard

- name: Ensure IP forwarding is enabled
  ansible.builtin.sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present
    reload: yes

- name: Enable and start WireGuard service
  ansible.builtin.systemd:
    name: "wg-quick@{{ wireguard_interface }}"
    enabled: yes
    state: started

- meta: flush_handlers
