prometheus_data_retention: "100d"
prometheus_version: "3.4.1"
prometheus_exposed_url: "{{ inventory_hostname }}"
prometheus_external_url: "https://{{ inventory_hostname }}/prometheus/"
prometheus_config_file: "{{ playbook_dir }}/../inventory/group_files/{{ group_names[0] }}/prometheus.yml"

blackbox_exporter_version: "0.26.0"
blackbox_targets_file: "{{ playbook_dir }}/../inventory/host_files/{{ inventory_hostname }}/web-targets.yml"
node_exporter_targets_file: "{{ playbook_dir }}/../inventory/host_files/{{ inventory_hostname }}/node_exporter_targets.yml"