---
- name: KardiAI Monitoring Setup
  hosts: kardi_monitoring
  become: yes

  roles:
    - base
    - firewall
    - docker
    - node_exporter
    - blackbox_exporter
    - prometheus
    - alertmanager
    - grafana
    - nginx
    - nginx-conf
    - certbot-nginx
