## EU Test env
# API services
- targets:
  - https://api.eu.kardi-ai.org/api/v1/general/liveness-probe
  labels:
    environment: test
- targets:
  - https://partner.eu.kardi-ai.org/api/v2/general/health-check
  labels:
    environment: test
- targets:
  - https://mb.eu.kardi-ai.org/api/v1/general/liveness-probe
  labels:
    environment: test
# web services
- targets:
  - https://web.eu.kardi-ai.org
  labels:
    environment: test
- targets:
  - https://web.eu.kardi-ai.org/static/favicon.e68d001a9fb1.svg
  labels:
    environment: test
- targets:
  - https://pay.eu.kardi-ai.org
  labels:
    environment: test
## EU Training env
# API services
- targets:
  - https://api.eu.ait.kardi-ai.org/api/v1/general/liveness-probe
  labels:
    environment: training
- targets:
  - https://mb.eu.ait.kardi-ai.org/api/v1/general/liveness-probe
  labels:
    environment: training
# web services
- targets:
  - https://web.eu.ait.kardi-ai.org
  labels:
    environment: training
- targets:
  - https://pay.eu.ait.kardi-ai.org
  labels:
    environment: training
## EU Production
# API services
- targets:
  - https://api.eu.kardi-ai.com/api/v1/general/liveness-probe
  labels:
    environment: production
- targets:
  - https://partner.eu.kardi-ai.com/api/v2/general/health-check
  labels:
    environment: production
- targets:
  - https://mb.eu.kardi-ai.com/api/v1/general/liveness-probe
  labels:
    environment: production
# web services
- targets:
  - https://web.eu.kardi-ai.com
  labels:
    environment: production
- targets:
  - https://web.eu.kardi-ai.com/static/favicon.e68d001a9fb1.svg
  labels:
    environment: production
- targets:
  - https://pay.eu.kardi-ai.com
  labels:
    environment: production
## UAE Production
# API services
- targets:
  - https://api.ae.kardi-ai.com/api/v1/general/liveness-probe
  labels:
    environment: "production UAE"
