
---
- name: Create Nginx configuration for Uptime Kuma
  ansible.builtin.template:
    src: nginx-uptime-kuma.conf.j2
    dest: "{{ uptime_kuma_nginx_config_path }}/uptime-kuma.conf"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: '0644'
    backup: true
  notify:
    - reload nginx
    - test nginx config
  tags: [nginx-config]

- name: Create Nginx configuration for Uptime Kuma
  ansible.builtin.template:
    src: nginx-uptime-status.conf.j2
    dest: "{{ uptime_kuma_nginx_config_path }}/uptime-status-page.conf"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: '0644'
    backup: true
  notify:
    - reload nginx
    - test nginx config
  tags: [nginx-config]
