# takes kubeconfig path from ENV
kubeconfig_path: "{{ lookup('env', 'KUBECONFIG') | default('~/.kube/config') }}"

# list of certificates issued on k8s cluster
ssl_secret_list:
  - name: "api-tls"
    namespace: "kardiai"
    cert_name: "api.kardi-ai.org"
  - name: "core-app-tls"
    namespace: "kardiai"
    cert_name: "web.kardi-ai.org"
  - name: "message-broker-tls"
    namespace: "kardiai"
    cert_name: "mb.kardi-ai.org"
  - name: "partner-api-tls"
    namespace: "kardiai"
    cert_name: "partner.kardi-ai.org"
  - name: "payment-service-tls"
    namespace: "kardiai"
    cert_name: "pay.kardi-ai.org"

# These should already be defined in your existing setup
#nginx_user: "nginx"
#nginx_group: "nginx"



