- name: Install prerequisites for apt repository
  apt:
    name: [ 'gnupg', 'curl', 'lsb-release', 'ca-certificates' ]
    state: present
    update_cache: yes

- name: Download nginx.org signing key (ASCII)
  ansible.builtin.get_url:
    url: "{{ nginx_repo_key_url }}"
    dest: /tmp/nginx_signing.key
    mode: '0644'

- name: Convert nginx.org key to dearmored format
  ansible.builtin.command: "gpg --dearmor /tmp/nginx_signing.key"
  args:
    creates: /tmp/nginx_signing.key.gpg

- name: copy nginx.org key to keyring
  ansible.builtin.copy:
    src: /tmp/nginx_signing.key.gpg
    dest: /usr/share/keyrings/nginx-archive-keyring.gpg
    mode: '0644'
    remote_src: yes

- name: Add nginx.org repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] {{ nginx_repo_url }} {{ nginx_ubuntu_codename }} {{ nginx_package_name }}"
    state: present
    filename: nginx

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install nginx
  apt:
    name: nginx
    state: present
