- name: Install prerequisite packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/{{ ansible_lsb.id | lower }}/gpg
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg
    state: present

- name: Add Docker APT repository
  ansible.builtin.apt_repository:
    repo: |
      deb [arch={{ docker_arch }} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/{{ ansible_lsb.id | lower }} {{ ansible_lsb.codename }} stable
    filename: docker
    state: present

- name: Update APT cache
  apt:
    update_cache: yes

- name: Install Docker CE packages
  apt:
    name: "{{ docker_packages }}"
    state: latest

- name: Ensure Docker service is enabled and started
  ansible.builtin.systemd:
    name: docker
    enabled: yes
    state: started

- name: Add current user to docker group (optional)
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
