---
# Email address for Let's Encrypt registrations
certbot_email: "admin@example.com"

# ssl

# List of domains to obtain certificates for
certbot_domains: []

# Use Let's Encrypt staging environment? (true/false)
certbot_staging: true

# Command to run after successful renewal (e.g., reload nginx)
certbot_renew_hook: "systemctl reload nginx"
